name: Publish Python 🐍 distribution to PyPI

on:
  push:
    branches: 
      - main
    tags:
      - 'v*.*.*'

jobs:
  build-and-publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install build dependencies
        run: |
          sudo apt install libnanoflann-dev
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build
      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}
          path: dist/*

  publish:
    needs: build-and-publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist-ubuntu-latest
          path: dist
      - uses: actions/download-artifact@v4
        with:
          name: dist-windows-latest
          path: dist
      - uses: actions/download-artifact@v4
        with:
          name: dist-macos-latest
          path: dist
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
