name: Publish Python 🐍 distribution to PyPI

on:
  push:
    branches: 
      - main
    tags:
      - 'v*.*.*'

jobs:
  build-wheels-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnanoflann-dev
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install cibuildwheel
        run: python -m pip install --upgrade pip cibuildwheel
      - name: Build wheels with cibuildwheel
        run: |
          python -m cibuildwheel --output-dir dist
      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-ubuntu-latest
          path: dist/*

  publish:
    needs: build-wheels-linux
    runs-on: ubuntu-latest
    permissions:
      id-token: write 
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist-ubuntu-latest
          path: dist

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
