name: Publish Python 🐍 distribution to PyPI
permissions:
  id-token: write

on:
  push:
    branches: 
      - main
    tags:
      - 'v*.*.*'

jobs:
  build-wheels-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install system dependencies
        run: |
          sudo apt install libnanoflann-dev

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install pybind11 setuptools wheel twine

      - name: Build wheels
        run: |
          python setup.py sdist bdist_wheel
          # remove source files
          rm dist/*.tar.gz

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-ubuntu-latest
          path: dist/*

  publish:
    needs: build-wheels-linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist-ubuntu-latest
          path: dist

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twine

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: twine upload dist/*
